{
 "title": "DownDetector",
 "description": "Monitoramento sites Down Detector",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 0, "y": 0 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/whatsapp.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Whatsapp",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 1, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Whatsapp" },
     "itemTag": { "filter": "Application: Site" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 3, "y": 0 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/spotify.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Spotify",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Spotify" },
     "itemTag": { "filter": "Application: Site" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 6, "y": 0 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/sefaz.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Sefaz",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Sefaz" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 9, "y": 0 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/bf.jpg\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Battlefield",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Battlefield" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 12, "y": 0 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/hbo-go.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "HBO",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "HBO" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 15, "y": 0 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/ICloud_logo.svg.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "iCloud",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "iCloud" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 18, "y": 0 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/epic.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Epic Games Store",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Epic Games Store" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 21, "y": 0 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/claro.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Claro",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Claro" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 0, "y": 2 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/Telegram_logo.svg.webp\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Telegram",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 1, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Telegram" },
     "itemTag": { "filter": "Application: Site" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 3, "y": 2 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/skype.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Skype",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Skype" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 6, "y": 2 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/nfe.webp\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Nota fiscal eletrônica",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Nota fiscal eletrônica" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 9, "y": 2 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/pubg.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "PUBG Play battlegrounds",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "PUBG Play battlegrounds" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 12, "y": 2 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/reddit.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Reddit",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Reddit" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 15, "y": 2 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/tinder.webp\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Tinder",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Tinder" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 18, "y": 2 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/garena.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Garena",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Garena" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 21, "y": 2 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/vivo.jpg\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Vivo",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Vivo" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 0, "y": 4 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/Instagram.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Instagram",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 1, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Instagram" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 3, "y": 4 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/google.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Google",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Google" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 6, "y": 4 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/ecac.jpg\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "eCAC",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "eCAC" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 9, "y": 4 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/fifa.webp\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Fifa",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Fifa" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 12, "y": 4 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/tiktok.webp\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Tiktok",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Tiktok" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 15, "y": 4 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/apple-tv.webp\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Apple-tv-plus",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Apple-tv-plus" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 18, "y": 4 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/deezer.jpg\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Deezer",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Deezer" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 21, "y": 4 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/oi.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Oi",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Oi" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 0, "y": 6 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/remontti/downdetector_zbx_grafana/master/icons/facebook.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Facebook",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 1, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Facebook" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 3, "y": 6 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/twitter.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Twitter",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Twitter" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 6, "y": 6 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/locaweb.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Locaweb",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Locaweb" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 9, "y": 6 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/appstore.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "App Store",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "App Store" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 12, "y": 6 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/anydesk.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Anydesk",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Anydesk" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 15, "y": 6 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/messenfer.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Facebook Messenger",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Facebook Messenger" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 18, "y": 6 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/eshop.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Nintendo-eshop",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Nintendo-eshop" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 21, "y": 6 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/tim.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "TIM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "TIM" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 0, "y": 8 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/remontti/downdetector_zbx_grafana/master/icons/youtube.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Youtube",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 1, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Youtube" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 3, "y": 8 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/office365.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Microsoft 365",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Office 365" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 6, "y": 8 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/hostgator.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Hostgator",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Hostgator" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 9, "y": 8 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/google%20play.avif\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Google Play",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Google Play" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 12, "y": 8 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/Telegram_logo.svg.webp\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Teamviewer",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Teamviewer" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 15, "y": 8 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/facetime.webp\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Facetime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Facetime" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 18, "y": 8 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/nubank.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Nubank",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Nubank" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 21, "y": 8 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/avianca.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Avianca",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Avianca" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 0, "y": 10 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/remontti/downdetector_zbx_grafana/master/icons/netflix.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Netflix",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 1, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Netflix" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 3, "y": 10 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/sicoob.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Sicoob",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Sicoob" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 6, "y": 10 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/kinghost.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "KingHost",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "KingHost" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 9, "y": 10 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/twitch.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Twitch",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Twitch" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 12, "y": 10 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/steam.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Steam",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Steam" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 15, "y": 10 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/sisu.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "SiSU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "SiSU" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 18, "y": 10 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/snapchat.webp\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Snapchat",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Snapchat" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 21, "y": 10 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/Gol_logo.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Gol",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Gol" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 0, "y": 12 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/remontti/downdetector_zbx_grafana/master/icons/caixa.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Caixa",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 1, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Caixa Econômica Federal" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 3, "y": 12 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/bradesco.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Bradesco",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Bradesco" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 6, "y": 12 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/hostnet.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Hostnet",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Hostnet" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 9, "y": 12 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/discord.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Discord",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Discord" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 12, "y": 12 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/xp.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "XP Investimentos",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "XP Investimentos" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 15, "y": 12 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/banrisul.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Banrisul",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Banrisul" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 18, "y": 12 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/yahoo.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Yahoo",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Yahoo" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 21, "y": 12 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/azul.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Azul",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Azul" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 0, "y": 14 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/remontti/downdetector_zbx_grafana/master/icons/amazon-prime.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Amazon Prime Video",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 1, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Amazon Prime Video" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 3, "y": 14 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/bancodobrasil.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Banco do Brasil",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Banco do Brasil" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 6, "y": 14 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/fortnite.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Fortnite",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Fortnite" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 9, "y": 14 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/lol.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "League of Legends",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "League of Legends" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 12, "y": 14 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/disney-plus.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disney-plus",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Disney-plus" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 15, "y": 14 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/amazon.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Amazon",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Amazon" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 18, "y": 14 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/yahoomail.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Yahoo Mail",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Yahoo Mail" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 21, "y": 14 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/esocial.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "eSocial",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "eSocial" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 0, "y": 16 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/remontti/downdetector_zbx_grafana/master/icons/amazon-web-services.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Amazon Web Services",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 1, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Amazon Web Services" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 3, "y": 16 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/itau.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Banco Itaú",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Banco Itaú" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 6, "y": 16 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/cod.jpg\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Call of Duty",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Call of Duty" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 9, "y": 16 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/dota2.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Dota 2",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Dota 2" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 12, "y": 16 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/google%20drive.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Google Drive",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Google Drive" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 15, "y": 16 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/github.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "GitHub",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "GitHub" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 18, "y": 16 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/tre.jpg\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Tribunal Superior Eleitoral",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Tribunal Superior Eleitoral" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 21, "y": 16 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/plex.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Plex",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Plex" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 0, "y": 18 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/remontti/downdetector_zbx_grafana/master/icons/gmail.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Gmail",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 1, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Gmail" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 3, "y": 18 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/c6.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "C6 Bank",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "C6 Bank" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 6, "y": 18 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/PSN-Logo-PNG-Image.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Playstation Network",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Playstation Network" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 9, "y": 18 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/correios.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Correios",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Correios" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 12, "y": 18 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/cloudflare.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cloudflare",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Cloudflare" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 15, "y": 18 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/globoplay.jpg\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Globoplay",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Globoplay" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 18, "y": 18 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/bing.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Bing",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Bing" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 21, "y": 18 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/dropbox.webp\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Dropbox",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Dropbox" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 0, "y": 20 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/remontti/downdetector_zbx_grafana/master/icons/mercado-livre.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Mercado Livre",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 1, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Mercado Livre" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 3, "y": 20 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/banco-inter.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Banco Inter",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Banco Inter" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 6, "y": 20 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/xbox.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Xbox Live",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Xbox Live" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 9, "y": 20 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/paramotn.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Paramountplus",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Paramountplus" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 12, "y": 20 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/linked.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "LinkedIn",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "LinkedIn" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 15, "y": 20 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/globo.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Globo",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Globo" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 18, "y": 20 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/receita%20federal.jpg\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Receita Federal",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Receita Federal" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 21, "y": 20 },
   "options": {
    "content": "<center><img src=\"https://raw.githubusercontent.com/botinhadigao/grafana-downdt/main/icones-png/uber.png\" style=\"width:48px;height:48px;\"></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uber",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "DOWNDETECTOR" },
     "host": { "filter": "DOWNDETECTOR" },
     "item": { "filter": "Uber" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  }
 ]
}